server:
  port: 9999
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.xa.DruidXADataSource
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root
        password: 0
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_user2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root
        password: 0
        initialSize: 5
        minIdle: 5
        maxActive: 20